#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

$app = new App();
$app->loadEnv();
if (is_file(__DIR__ . DIRECTORY_SEPARATOR . '.env.local')) {
    $app->setEnvName('local');
}

// 应用初始化
$app->console->run();
